# Generated by Django 5.1.5 on 2025-09-01 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('old_registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_job', models.CharField(blank=True, max_length=150, null=True)),
                ('grandfather_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=150, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('registration_place_number', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('school_join_date', models.DateField(blank=True, null=True)),
                ('previous_high_school', models.CharField(blank=True, max_length=200, null=True)),
                ('admission_doc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_doc_date', models.DateField(blank=True, null=True)),
                ('joined_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('failed_grades_before_joining', models.TextField(blank=True, null=True)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('leaving_reason', models.TextField(blank=True, null=True)),
                ('next_high_school', models.CharField(blank=True, max_length=200, null=True)),
                ('leaving_doc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('leaving_doc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('leaving_doc_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('result', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='web.student')),
            ],
        ),
    ]
