<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-17 16:52
=======
# Generated by Django 5.1.5 on 2025-09-01 03:15
>>>>>>> 16330f09d40fdf7114f9bdfafeddda4cc1a8565e

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('auth', '0012_alter_user_first_name_max_length'),
=======
>>>>>>> 16330f09d40fdf7114f9bdfafeddda4cc1a8565e
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, unique=True)),
=======
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
>>>>>>> 16330f09d40fdf7114f9bdfafeddda4cc1a8565e
                ('old_registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_job', models.CharField(blank=True, max_length=150, null=True)),
                ('grandfather_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=150, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('registration_place_number', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('school_join_date', models.DateField(blank=True, null=True)),
                ('previous_high_school', models.CharField(blank=True, max_length=200, null=True)),
                ('admission_doc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_doc_date', models.DateField(blank=True, null=True)),
                ('joined_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('failed_grades_before_joining', models.TextField(blank=True, null=True)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('leaving_reason', models.TextField(blank=True, null=True)),
                ('next_high_school', models.CharField(blank=True, max_length=200, null=True)),
                ('leaving_doc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('leaving_doc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('leaving_doc_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=150, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=150, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('specialization', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> 16330f09d40fdf7114f9bdfafeddda4cc1a8565e
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('result', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='web.student')),
            ],
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('teachers', models.ManyToManyField(blank=True, related_name='subjects', to='web.teacher')),
            ],
        ),
=======
>>>>>>> 16330f09d40fdf7114f9bdfafeddda4cc1a8565e
    ]
