# Generated by Django 5.2.7 on 2025-10-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='serial_number',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='serial_number',
            new_name='id_number',
        ),
    ]
